### ISSUE TITLE
No navigation controls in article screen

### ISSUE THREAD

**Issue by ctiedt** [schul-cloud/schulcloud-flutter#51]
**Describe the bug**
This might be less of a bug and more of an omission, but there are no navigation controls on the article screen.

**To Reproduce**
1. Go to 'News' in the navigation bar
2. Click on any article
3. The article itself appears but has no navigation controls.

**Expected behavior**
Just like any other screen in this app, a bottom navigation bar should be displayed. In this case, a normal `AppBar` with the article title and an option to return to the news screen would be useful as well.

**Comment by MarcelGarus** [comment]
Working on it. This is already fixed in the `improve-files` branch (so sorry about the naming, I got carried away by fixing so many little things).
It revamps the whole navigation system so another `Navigator` is used when logged in (not the default one of the `MaterialApp`). That means, by default the bottom bar remains visible everywhere.
